### ISSUE TITLE
I get an infinite loop in ConvexHull.prototype.compute

### ISSUE THREAD

**Issue by geon** [Kcnarf/d3-weighted-voronoi#10]
next.conflicts.isEmpty() is false, so current is not increased
this.visible[jF].getHorizon() is null
this.horizon.length is 0
first and last are null
this.created.length is 0, so current is not increased

repeat...

Input to _weightedVoronoi :

[[0.3,-1.5,1.7542563288623765],[-0.3,-1.5,1.7542563288623765],[0.3,-0.8999999999999999,1.7542563288623765],[-0.3,-0.8999999999999999,1.7542563288623765],[-0.3,-0.3,1.7542563288623765],[-0.8999999999999999,-0.8999999999999999,1.7542563288623765],[0.8999999999999999,-1.5,1.7542563288623765],[-0.8999999999999999,-1.5,1.7542563288623765]]

**Comment by geon** [comment]
It seems _weightedVoronoi chokes on these coordinates:

			[0.3, -1, 1],
			[-0.3, -1, 1],
			[0.3, -0.8999999999999999, 1],
			[-0.3, -0.8999999999999999, 1]

**Comment by Kcnarf** [comment]
Hi,
I found some time to look at this issue, and the corresponding pull request.

I admit that this part of the code is quite opaque for me :/ . The root code is a Java implementation (https://github.com/ArlindNocaj/power-voronoi-diagram from Arlind Nocaj, cf. the README's Reference section), that has been ported to JS (https://bl.ocks.org/mkedwards/759e719eefe36cf9c8ab from Michael K. Edwards), that I somehow patiently debug (https://bl.ocks.org/kcnarf/15d54f4ccae6a3710cd3029546664eec) and test.

Without any deep investigation, one thing that looks to me quite astonishing is that all the data points are OUT of the clipping polygon (clipping polygon = the enclosing shape that have to be tessellated/segmented in several cells) : the default clipping polygon is the unit square (0 =< x =<1; 0 =< y =<1), but all the data points have a y-coordinate < 0.
Nonetheless, the issue is still happening even when the clipping polygon is redefined in order to enclose all the data points.

**Comment by Kcnarf** [comment]
I find a fix, that I post here before going into the test/versioning/deploy pipeline.

I think it is linked to a floating precision issue in https://github.com/Kcnarf/d3-weighted-voronoi/blob/7fb47a72dffa78e37a5441c2825e076080e10303/src/convexHull.js#L69

Replacing the above line with
```if (!epsilonesque(dot(f0.normal, f0.verts[0]) - dot(f0.normal, this.points[i]))) {```
makes the all thing works as a charm.

note: you should ```import { epsilonesque, dot, linearDependent } from './utils';```at the begining of the file.
