### ISSUE TITLE
why is index == 0 for all cells?

### ISSUE THREAD

**Issue by Fil** [Kcnarf/d3-weighted-voronoi#6]
Two questions about the cell<->site correspondance

1. How can I easily get all points that have no matching cell? In the classic (non-weighted) voronoi, all cells are returned in the same order as the points, but here it seems different. 

2. In https://observablehq.com/d/128a52368e482305 I can see that for all cells we have cell.site.index == 0. Is this expected?

**Comment by Kcnarf** [comment]
If `c` is a cell, `c.site.originalObject` references the underlying data, and is the stable way to link cells and data. Hence, if `cells` the set of all cells, `cells.map(c => c.site.originalObject)` is an array of the subset of data that produces a cell. You can use it to check if a datum produces (or not) a cell.
 
The order of the cells are not the same as the order of the data because some data may not produce any cell. In such a situation, the length of the cells array is lower than the length of the data array. Hence, I don't even try to order the cell array with regards to the data array.

Regarding the _`index ===0` in all cell_ issue, I guess this is relic of an old version of the code. Let me check.

**Comment by Kcnarf** [comment]
`index` is used internally when it comes to produce the final cells (in [convexHull.js](https://github.com/Kcnarf/d3-weighted-voronoi/blob/045789f0897103c7ecae4fcfb03b9cf24e96a7b0/src/convexHull.js#L39)).

edit (13/11/2020): I admit I don't put effort on distinguishing stable attributes that user can use and rely on (as site.initialObject), to internal attributes that may change over releases.
